# Generated by Django 5.2.14 on 2026-09-14 17:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_alter_invoice_subscription_alter_payment_invoice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='monthly_discount_percent',
            field=models.PositiveIntegerField(default=0, help_text='% off the monthly price, shown on the landing page', validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='plan',
            name='yearly_discount_percent',
            field=models.PositiveIntegerField(default=0, help_text='% off the yearly price, shown on the landing page', validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
