# Generated by Django 5.2.14 on 2026-09-14 17:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_plan_monthly_discount_percent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='monthly_discount_percent',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='% off the monthly price, shown on the landing page', validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='plan',
            name='yearly_discount_percent',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='% off the yearly price, shown on the landing page', validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
