# Generated by Django 5.2.14 on 2026-09-14 17:27

from django.db import migrations, models


def hide_free_plans_from_landing_page(apps, schema_editor):
    """Preserve current landing-page behavior: only paid plans were shown
    (via a monthly_price>0 filter) before this explicit checkbox existed —
    default new plans to visible, but keep any free-tier plan hidden."""
    Plan = apps.get_model("billing", "Plan")
    db_alias = schema_editor.connection.alias
    Plan.objects.using(db_alias).filter(monthly_price=0).update(show_on_landing_page=False)


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_alter_plan_monthly_discount_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='show_on_landing_page',
            field=models.BooleanField(default=True, help_text='Show this plan in the public pricing section on the landing page'),
        ),
        migrations.RunPython(hide_free_plans_from_landing_page, migrations.RunPython.noop),
    ]
