# Generated by Django 5.2.14 on 2026-09-15 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_plan_show_on_landing_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='historical_months_limit',
            field=models.PositiveIntegerField(default=1, help_text='How many months back a customer on this plan may create or backdate a transaction.'),
        ),
    ]
