# Generated by Django 5.2.14 on 2026-09-15 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_plan_historical_months_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='entry_floor_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
