# Generated by Django 5.2.14 on 2026-09-15 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_subscription_entry_floor_date'),
        ('organizations', '0003_organization_service_status_servicestatuschange'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('code', models.CharField(help_text='What the customer types in, e.g. SUMMER25', max_length=40, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('discount_type', models.CharField(choices=[('PERCENT', 'Percentage'), ('FLAT', 'Flat amount')], default='PERCENT', max_length=10)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='A percentage (0-100) or a flat currency amount, depending on Discount type.', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('valid_from', models.DateField(blank=True, help_text='Blank = usable immediately', null=True)),
                ('valid_until', models.DateField(blank=True, help_text='Blank = never expires', null=True)),
                ('max_redemptions', models.PositiveIntegerField(blank=True, help_text='Total number of times this code may be used, across all organizations. Blank = unlimited.', null=True)),
                ('max_redemptions_per_org', models.PositiveIntegerField(default=1, help_text='How many times a single organization may use this code.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CouponRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('redeemed_at', models.DateTimeField(auto_now_add=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='billing.coupon')),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_redemption', to='billing.invoice')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_redemptions', to='organizations.organization')),
            ],
            options={
                'ordering': ['-redeemed_at'],
                'indexes': [models.Index(fields=['coupon', 'organization'], name='billing_cou_coupon__1baa58_idx')],
            },
        ),
    ]
