# Generated by Django 5.2.14 on 2026-09-15 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_coupon_couponredemption'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='razorpay_monthly_plan_id',
            field=models.CharField(blank=True, editable=False, max_length=50),
        ),
        migrations.AddField(
            model_name='plan',
            name='razorpay_yearly_plan_id',
            field=models.CharField(blank=True, editable=False, max_length=50),
        ),
        migrations.AddField(
            model_name='subscription',
            name='autopay_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscription',
            name='razorpay_subscription_id',
            field=models.CharField(blank=True, editable=False, max_length=50),
        ),
    ]
