# Generated by Django 5.2.14 on 2026-09-21 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_plan_razorpay_monthly_plan_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='discount_type',
            field=models.CharField(choices=[('PERCENT', 'Percentage'), ('FLAT', 'Flat amount off'), ('FIXED_PRICE', 'Fixed price (client pays only this)')], default='PERCENT', max_length=20),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, help_text='A percentage (0-100), a flat amount to take off, or - for Fixed price - the amount the client will pay.', max_digits=10),
        ),
    ]
