# Generated by Django 5.2.14 on 2026-09-22 14:09

from django.db import migrations, models


def bump_old_default_to_three_months(apps, schema_editor):
    """Existing plan rows were saved with the old default of 1 month;
    raise those (and only those — a superadmin's own custom value is left
    alone) to the new 3-month default."""
    Plan = apps.get_model("billing", "Plan")
    Plan.objects.using(schema_editor.connection.alias).filter(historical_months_limit=1).update(
        historical_months_limit=3
    )


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0013_alter_coupon_discount_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='historical_months_limit',
            field=models.PositiveIntegerField(default=3, help_text='How many months back a customer on this plan may create or backdate a transaction.'),
        ),
        migrations.RunPython(bump_old_default_to_three_months, migrations.RunPython.noop),
    ]
