# Generated by Django 5.2.14 on 2026-09-25 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0014_alter_plan_historical_months_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='autopay_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
