# Generated by Django 5.2.12 on 2026-10-05 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0015_subscription_autopay_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='service_billing_end_date',
            field=models.DateField(blank=True, help_text='End date of the service period being billed', null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='service_billing_start_date',
            field=models.DateField(blank=True, help_text='Start date of the service period being billed', null=True),
        ),
    ]
