# Generated by Django 5.2.14 on 2026-09-14 21:03

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_subcategory_expenseentry_subcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseentry',
            name='product_category',
            field=models.ForeignKey(blank=True, limit_choices_to={'kind': 'PRODUCT'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases_as_product_category', to='finance.category'),
        ),
        migrations.AddField(
            model_name='salesentry',
            name='product_category',
            field=models.ForeignKey(blank=True, limit_choices_to={'kind': 'PRODUCT'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_as_product_category', to='finance.category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='kind',
            field=models.CharField(choices=[('SALES', 'Sales channel'), ('EXPENSE', 'Expense category'), ('PURCHASE', 'Purchase category'), ('PRODUCT', 'Product category')], max_length=10),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.CharField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('name',), name='finance_customer_name_uniq')],
            },
        ),
        migrations.AddField(
            model_name='salesentry',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_entries', to='finance.customer'),
        ),
        migrations.CreateModel(
            name='Payable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vendor', models.CharField(max_length=150)),
                ('bill_date', models.DateField(default=datetime.date.today)),
                ('due_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_by_email', models.CharField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product_category', models.ForeignKey(blank=True, limit_choices_to={'kind': 'PRODUCT'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payables', to='finance.category')),
            ],
            options={
                'ordering': ['due_date', '-created_at'],
                'indexes': [models.Index(fields=['due_date'], name='finance_pay_due_dat_e279f1_idx')],
            },
        ),
        migrations.CreateModel(
            name='Receivable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_date', models.DateField(default=datetime.date.today)),
                ('due_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('amount_received', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_by_email', models.CharField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receivables', to='finance.customer')),
                ('product_category', models.ForeignKey(blank=True, limit_choices_to={'kind': 'PRODUCT'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receivables', to='finance.category')),
            ],
            options={
                'ordering': ['due_date', '-created_at'],
                'indexes': [models.Index(fields=['due_date'], name='finance_rec_due_dat_c6d8a1_idx')],
            },
        ),
    ]
