# Generated by Django 5.2.14 on 2026-09-14 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
