# Generated by Django 5.2.14 on 2026-09-14 21:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_vendor_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='opening_balance_as_on',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
