# Generated by Django 5.2.14 on 2026-09-14 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_vendor_opening_balance_as_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseentry',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesentry',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
