# Generated by Django 5.2.12 on 2026-09-16 18:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_partner_partnertransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='partner',
            name='opening_balance_as_on',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
