# Generated by Django 5.2.14 on 2026-09-17 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_partner_opening_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='gst_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Applied to every sale/purchase logged under this category, for the GST Summary report.', max_digits=5, verbose_name='GST rate %'),
        ),
    ]
