# Generated by Django 5.2.14 on 2026-09-17 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_category_gst_rate'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subcategory',
            name='finance_subcategory_category_name_uniq',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='finance.subcategory'),
        ),
        migrations.AlterField(
            model_name='category',
            name='kind',
            field=models.CharField(choices=[('SALES', 'Revenue channel'), ('EXPENSE', 'Expense category'), ('PURCHASE', 'Purchase category'), ('PRODUCT', 'Product category')], max_length=10),
        ),
        migrations.AddConstraint(
            model_name='subcategory',
            constraint=models.UniqueConstraint(fields=('category', 'parent', 'name'), name='finance_subcategory_category_parent_name_uniq'),
        ),
    ]
