# Generated by Django 5.2.14 on 2026-09-25 19:16

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_remove_subcategory_finance_subcategory_category_name_uniq_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g. "Current Account" or "Salary Account"', max_length=150)),
                ('bank_name', models.CharField(choices=[('SBI', 'State Bank of India'), ('HDFC', 'HDFC Bank'), ('ICICI', 'ICICI Bank'), ('AXIS', 'Axis Bank'), ('KOTAK', 'Kotak Mahindra Bank'), ('PNB', 'Punjab National Bank'), ('BOB', 'Bank of Baroda'), ('CANARA', 'Canara Bank'), ('UNION', 'Union Bank of India'), ('IDBI', 'IDBI Bank'), ('YES', 'Yes Bank'), ('INDUSIND', 'IndusInd Bank'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('other_bank_name', models.CharField(blank=True, help_text='Name of the bank, if not listed above', max_length=100)),
                ('account_number', models.CharField(blank=True, help_text='Optional — full number or last 4 digits', max_length=50)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('opening_balance_as_on', models.DateField(default=datetime.date.today)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('name',), name='finance_bankaccount_name_uniq')],
            },
        ),
        migrations.AddField(
            model_name='cashtransfer',
            name='bank_account',
            field=models.ForeignKey(blank=True, help_text='Which bank account this deposit/withdrawal moved to or from (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers', to='finance.bankaccount'),
        ),
        migrations.AddField(
            model_name='expenseentry',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_entries', to='finance.bankaccount'),
        ),
        migrations.AddField(
            model_name='partnertransaction',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_transactions', to='finance.bankaccount'),
        ),
        migrations.AddField(
            model_name='purchaseentry',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_entries', to='finance.bankaccount'),
        ),
        migrations.AddField(
            model_name='salesentry',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_entries', to='finance.bankaccount'),
        ),
    ]
