# Generated by Django 5.2.12 on 2026-09-30 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_bankaccount_cashtransfer_bank_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesentry',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='salesentry',
            name='gross_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
