# Generated by Django 5.2.12 on 2026-10-03 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0014_salesentry_discount_salesentry_gross_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankaccount',
            options={'base_manager_name': 'objects', 'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='cashtransfer',
            options={'base_manager_name': 'objects', 'ordering': ['-date', '-created_at'], 'verbose_name': 'Cash/bank transfer'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'base_manager_name': 'objects', 'ordering': ['kind', 'name']},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'base_manager_name': 'objects', 'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='expenseentry',
            options={'base_manager_name': 'objects', 'ordering': ['-date', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='financesettings',
            options={'base_manager_name': 'objects', 'verbose_name': 'Finance settings', 'verbose_name_plural': 'Finance settings'},
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={'base_manager_name': 'objects', 'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='partnertransaction',
            options={'base_manager_name': 'objects', 'ordering': ['-date', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='payable',
            options={'base_manager_name': 'objects', 'ordering': ['due_date', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='purchaseentry',
            options={'base_manager_name': 'objects', 'ordering': ['-date', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='receivable',
            options={'base_manager_name': 'objects', 'ordering': ['due_date', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='salesentry',
            options={'base_manager_name': 'objects', 'ordering': ['-date', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'base_manager_name': 'objects', 'ordering': ['category', 'name'], 'verbose_name_plural': 'Subcategories'},
        ),
        migrations.AlterModelOptions(
            name='vendor',
            options={'base_manager_name': 'objects', 'ordering': ['name']},
        ),
    ]
