# Generated by Django 5.2.12 on 2026-10-10 14:18

import apps.sheets_store.mixin
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0019_financesettings_bulk_column_labels'),
        ('organizations', '0021_cloudbackupconnection_connected_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='KickbackEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bill_number', models.CharField(max_length=50)),
                ('admission_date', models.DateField()),
                ('discharge_date', models.DateField(blank=True, null=True)),
                ('amount_received', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('consulting_doctor', models.CharField(blank=True, max_length=150, verbose_name='Consulting doctor')),
                ('referred_by', models.CharField(blank=True, max_length=150)),
                ('final_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('kickback_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_by_email', models.CharField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Kickback entry',
                'ordering': ['-admission_date', '-created_at'],
                'base_manager_name': 'objects',
                'indexes': [models.Index(fields=['admission_date'], name='finance_kic_admissi_51cd63_idx')],
            },
            bases=(apps.sheets_store.mixin.SheetAwareModelMixin, models.Model),
        ),
    ]
