# Generated by Django 5.2.12 on 2026-10-10 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0020_kickbackentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='kickbackentry',
            name='ref_date',
            field=models.DateField(blank=True, help_text='Date the amount was paid', null=True, verbose_name='Ref date'),
        ),
    ]
