# Generated by Django 5.2.12 on 2026-10-10 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0022_general_ledger'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalledger',
            name='note',
        ),
        migrations.AddField(
            model_name='generalledger',
            name='district',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='generalledger',
            name='mandal',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='generalledger',
            name='profession',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='generalledger',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='generalledger',
            name='village',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
