# Generated by Django 5.2.12 on 2026-10-10 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0023_general_ledger_profile_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalledger',
            name='note',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
