# Generated by Django 5.2.12 on 2026-10-10 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0024_general_ledger_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseentry',
            name='paid_to_ledger',
            field=models.ForeignKey(blank=True, help_text='The general ledger this payment went to (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_payments', to='finance.generalledger'),
        ),
    ]
