# Generated by Django 5.2.12 on 2026-10-10 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0025_expenseentry_paid_to_ledger'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseentry',
            name='kickback_bill',
            field=models.ForeignKey(blank=True, help_text='The kickback bill this payment relates to (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='finance.kickbackentry'),
        ),
        migrations.AddField(
            model_name='kickbackentry',
            name='patient_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='kickbackentry',
            name='patient_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
