# Generated by Django 5.2.12 on 2026-10-10 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0026_kickback_patient_expense_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='financesettings',
            name='kickback_column_labels',
            field=models.TextField(blank=True, default=''),
        ),
    ]
