# Generated by Django 5.2.12 on 2026-10-10 16:43

import apps.sheets_store.mixin
import django.db.models.deletion
import uuid
from django.db import migrations, models


def create_payments_from_existing_bills(apps, schema_editor):
    KickbackEntry = apps.get_model("finance", "KickbackEntry")
    KickbackPayment = apps.get_model("finance", "KickbackPayment")
    for bill in KickbackEntry.objects.filter(amount_received__gt=0):
        KickbackPayment.objects.create(
            organization_id=bill.organization_id,
            bill=bill,
            paid_on=bill.ref_date or bill.admission_date,
            amount=bill.amount_received,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0027_financesettings_kickback_column_labels'),
        ('organizations', '0021_cloudbackupconnection_connected_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='KickbackPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('paid_on', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='finance.kickbackentry')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Kickback payment',
                'ordering': ['paid_on', 'created_at'],
                'base_manager_name': 'objects',
            },
            bases=(apps.sheets_store.mixin.SheetAwareModelMixin, models.Model),
        ),
        migrations.RunPython(create_payments_from_existing_bills, migrations.RunPython.noop),
    ]
