# Generated by Django 5.2.12 on 2026-10-10 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0028_kickback_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesentry',
            name='kickback_bill',
            field=models.ForeignKey(blank=True, help_text='The kickback bill this receipt relates to (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_sales', to='finance.kickbackentry'),
        ),
        migrations.DeleteModel(
            name='KickbackPayment',
        ),
    ]
