# Generated by Django 5.2.12 on 2026-10-10 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0029_revenue_kickback_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='kickbackentry',
            name='referred_by_ledger',
            field=models.ForeignKey(blank=True, help_text='The general ledger of the person who referred this bill (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_bills', to='finance.generalledger'),
        ),
    ]
