# Generated by Django 5.2.12 on 2026-10-10 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0030_kickbackentry_referred_by_ledger'),
    ]

    operations = [
        migrations.AddField(
            model_name='kickbackentry',
            name='consulting_doctor_ledger',
            field=models.ForeignKey(blank=True, help_text='The general ledger of the consulting doctor (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consulted_bills', to='finance.generalledger'),
        ),
    ]
