# Generated by Django 5.2.12 on 2026-10-10 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0031_kickbackentry_consulting_doctor_ledger'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kickbackentry',
            name='consulting_doctor_ledger',
        ),
        migrations.AddField(
            model_name='financesettings',
            name='kickback_doctor_category',
            field=models.ForeignKey(blank=True, help_text='Category whose sub-categories and items are the consulting doctors', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='finance.category'),
        ),
        migrations.AddField(
            model_name='kickbackentry',
            name='consulting_doctor_item',
            field=models.ForeignKey(blank=True, help_text="The hospital doctor, picked from the doctors' category set in Finance Settings (optional)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kickback_bills', to='finance.subcategory'),
        ),
    ]
