# Generated by Django 5.2.12 on 2026-10-10 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0032_kickback_doctor_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kickbackentry',
            name='referred_by_ledger',
        ),
        migrations.AlterField(
            model_name='kickbackentry',
            name='referred_by',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
