from django.urls import path
from django.views.generic import RedirectView

from .views import (
    AccountLedgerView,
    AddBankAccountView,
    AddCategoryView,
    AddKickbackEntryView,
    AgingReportView,
    ApplyCouponView,
    AddCustomerView,
    AddPartnerView,
    AddPartnerTransactionView,
    AddPayableView,
    AddReceivableView,
    AddSubcategoryView,
    AddTransferView,
    BankAccountLedgerView,
    BankAccountsView,
    DeleteTransferView,
    EditTransferView,
    AddVendorView,
    AnalyticsView,
    SubcategoryDetailView,
    BillingView,
    BulkAddExpensesView,
    BulkAddPurchasesView,
    SingleEntryView,
    BulkAddSalesView,
    CancelAutopayView,
    CashPositionView,
    CategoriesView,
    CategoryStatementCsvView,
    CategoryStatementExcelView,
    CategoryStatementPdfView,
    CategoryStatementView,
    CreateAutopaySubscriptionView,
    CreateInvoicePaymentOrderView,
    CustomerLedgerView,
    DailyBulkEntryView,
    DailyReportPdfView,
    DailyEntryDaysView,
    DailyReportView,
    DailySummaryDayDetailView,
    DailySummaryExcelView,
    DailySummaryPdfView,
    DailySummaryView,
    DashboardView,
    DeleteBankAccountView,
    DeleteCategoryView,
    DeleteKickbackEntryView,
    DeletePartnerTransactionView,
    EditBankAccountView,
    EditKickbackEntryView,
    EditPartnerTransactionView,
    EditPayableView,
    EditReceivableView,
    DeletePayableView,
    DeleteReceivableView,
    DeleteSubcategoryView,
    DeleteVendorView,
    EditCategoryView,
    EditSubcategoryView,
    EditVendorView,
    AddGeneralLedgerView,
    AddLedgerEntryView,
    DeleteGeneralLedgerView,
    DeleteLedgerEntryView,
    ExpenseCategoryTrendView,
    FinanceSettingsView,
    GeneralLedgerDetailView,
    ImportKickbackEntriesView,
    ImportSalesCommitView,
    ImportSalesSampleView,
    ImportSalesUploadView,
    InvoiceDetailView,
    KickbackColumnLabelsView,
    KickbackDetailView,
    KickbackEntriesPdfView,
    KickbackEntriesCsvView,
    KickbackEntriesExcelView,
    KickbackImportSampleView,
    KickbacksView,
    LedgersView,
    MonthlySummaryExcelView,
    MonthlySummaryPdfView,
    MonthlySummaryView,
    PartnerLedgerCsvView,
    PartnerLedgerExcelView,
    PartnerLedgerPdfView,
    PartnerLedgerView,
    PurchaseExpenseIntelligenceView,
    RecordPayablePaymentView,
    RecordReceivablePaymentView,
    ReportLineDetailView,
    ReportsView,
    SalesChannelTrendView,
    SalesIntelligenceDetailsView,
    SalesIntelligenceView,
    StatementPdfView,
    ToggleBankAccountView,
    ToggleCategoryView,
    ToggleCustomerView,
    ToggleSubcategoryView,
    ToggleVendorView,
    VendorLedgerView,
    VendorsView,
    VerifyAutopaySetupView,
    VerifyInvoicePaymentView,
)

app_name = "finance"

urlpatterns = [
    path("", DashboardView.as_view(), name="dashboard"),
    path("billing/", BillingView.as_view(), name="billing"),
    path("billing/invoices/<int:pk>/", InvoiceDetailView.as_view(), name="invoice_detail"),
    path(
        "billing/invoices/<int:pk>/pay/order/",
        CreateInvoicePaymentOrderView.as_view(),
        name="create_invoice_payment_order",
    ),
    path(
        "billing/invoices/<int:pk>/pay/verify/",
        VerifyInvoicePaymentView.as_view(),
        name="verify_invoice_payment",
    ),
    path(
        "billing/invoices/<int:pk>/coupon/",
        ApplyCouponView.as_view(),
        name="apply_coupon",
    ),
    path("billing/autopay/create/", CreateAutopaySubscriptionView.as_view(), name="create_autopay_subscription"),
    path("billing/autopay/verify/", VerifyAutopaySetupView.as_view(), name="verify_autopay_setup"),
    path("billing/autopay/cancel/", CancelAutopayView.as_view(), name="cancel_autopay"),
    path("analytics/", AnalyticsView.as_view(), name="analytics"),
    path("analytics/subcategory-detail/", SubcategoryDetailView.as_view(), name="subcategory_detail"),
    path("revenue-intelligence/", SalesIntelligenceView.as_view(), name="sales_intelligence"),
    path(
        "revenue-intelligence/details/",
        SalesIntelligenceDetailsView.as_view(),
        name="sales_intelligence_details",
    ),
    path(
        "revenue-intelligence/channel-trend/",
        SalesChannelTrendView.as_view(),
        name="sales_channel_trend",
    ),
    path(
        "cost-intelligence/",
        PurchaseExpenseIntelligenceView.as_view(),
        name="purchase_expense_intelligence",
    ),
    path(
        "cost-intelligence/expense-category-trend/",
        ExpenseCategoryTrendView.as_view(),
        name="expense_category_trend",
    ),
    path("daily/", DailyReportView.as_view(), name="daily_report"),
    path("daily-performance/", DailySummaryView.as_view(), name="daily_summary"),
    path(
        "daily-performance/day/<str:date>/",
        DailySummaryDayDetailView.as_view(),
        name="daily_summary_day_detail",
    ),
    # Old address, kept so existing bookmarks/links still land on the page.
    path("daily-summary/", RedirectView.as_view(pattern_name="finance:daily_summary", query_string=True)),
    path("daily-performance/export.xlsx", DailySummaryExcelView.as_view(), name="daily_summary_excel"),
    path("daily-performance/export.pdf", DailySummaryPdfView.as_view(), name="daily_summary_pdf"),
    path("daily/entry-days/", DailyEntryDaysView.as_view(), name="daily_entry_days"),
    path("daily/pdf",DailyReportPdfView.as_view(), name="daily_report_pdf"),
    path("daily/bulk-entry/", DailyBulkEntryView.as_view(), name="daily_bulk_entry"),
    path("daily/bulk-sales/", BulkAddSalesView.as_view(), name="bulk_add_sales"),
    path("daily/bulk-expenses/", BulkAddExpensesView.as_view(), name="bulk_add_expenses"),
    path("daily/bulk-purchases/", BulkAddPurchasesView.as_view(), name="bulk_add_purchases"),
    path("daily/single-entry/", SingleEntryView.as_view(), name="single_entry"),
    path("daily/import-sales/", ImportSalesUploadView.as_view(), name="import_sales"),
    path("daily/import-sales/sample.csv", ImportSalesSampleView.as_view(), name="import_sales_sample"),
    path("daily/import-sales/commit/", ImportSalesCommitView.as_view(), name="import_sales_commit"),
    path("transfers/add/", AddTransferView.as_view(), name="add_transfer"),
    path("transfers/<uuid:pk>/edit/", EditTransferView.as_view(), name="edit_transfer"),
    path("transfers/<uuid:pk>/delete/", DeleteTransferView.as_view(), name="delete_transfer"),
    path("reports/", ReportsView.as_view(), name="reports"),
    path("reports/line-detail/", ReportLineDetailView.as_view(), name="report_line_detail"),
    path("reports/monthly-summary/", MonthlySummaryView.as_view(), name="monthly_summary"),
    path("reports/monthly-summary/export.xlsx", MonthlySummaryExcelView.as_view(), name="monthly_summary_excel"),
    path("reports/monthly-summary/export.pdf", MonthlySummaryPdfView.as_view(), name="monthly_summary_pdf"),
    path("reports/category-statement/", CategoryStatementView.as_view(), name="category_statement"),
    path(
        "reports/category-statement/export.xlsx",
        CategoryStatementExcelView.as_view(),
        name="category_statement_excel",
    ),
    path(
        "reports/category-statement/export.csv",
        CategoryStatementCsvView.as_view(),
        name="category_statement_csv",
    ),
    path(
        "reports/category-statement/export.pdf",
        CategoryStatementPdfView.as_view(),
        name="category_statement_pdf",
    ),
    path("reports/pnl.pdf", StatementPdfView.as_view(statement="pnl"), name="pnl_pdf"),
    path(
        "reports/balance-sheet.pdf",
        StatementPdfView.as_view(statement="balance_sheet"),
        name="balance_sheet_pdf",
    ),
    path("reports/cash-flow.pdf", StatementPdfView.as_view(statement="cash_flow"), name="cash_flow_pdf"),
    path("reports/gst-summary.pdf", StatementPdfView.as_view(statement="gst"), name="gst_pdf"),
    path("setup/", FinanceSettingsView.as_view(), name="settings"),
    # Old address, kept so existing bookmarks/links still land on the page.
    path("settings/", RedirectView.as_view(pattern_name="finance:settings", query_string=True)),
    path("categories/", CategoriesView.as_view(), name="categories"),
    path("categories/add/", AddCategoryView.as_view(), name="add_category"),
    path("categories/<uuid:pk>/edit/", EditCategoryView.as_view(), name="edit_category"),
    path("categories/<uuid:pk>/toggle/", ToggleCategoryView.as_view(), name="toggle_category"),
    path("categories/<uuid:pk>/delete/", DeleteCategoryView.as_view(), name="delete_category"),
    path("subcategories/add/", AddSubcategoryView.as_view(), name="add_subcategory"),
    path("subcategories/<uuid:pk>/edit/", EditSubcategoryView.as_view(), name="edit_subcategory"),
    path("subcategories/<uuid:pk>/toggle/", ToggleSubcategoryView.as_view(), name="toggle_subcategory"),
    path("subcategories/<uuid:pk>/delete/", DeleteSubcategoryView.as_view(), name="delete_subcategory"),
    path("customers/add/", AddCustomerView.as_view(), name="add_customer"),
    path("customers/<uuid:pk>/toggle/", ToggleCustomerView.as_view(), name="toggle_customer"),
    path("vendors/", VendorsView.as_view(), name="vendors"),
    path("vendors/add/", AddVendorView.as_view(), name="add_vendor"),
    path("vendors/<uuid:pk>/edit/", EditVendorView.as_view(), name="edit_vendor"),
    path("vendors/<uuid:pk>/toggle/", ToggleVendorView.as_view(), name="toggle_vendor"),
    path("vendors/<uuid:pk>/delete/", DeleteVendorView.as_view(), name="delete_vendor"),
    path("bank-accounts/", BankAccountsView.as_view(), name="bank_accounts"),
    path("bank-accounts/add/", AddBankAccountView.as_view(), name="add_bank_account"),
    path("bank-accounts/<uuid:pk>/edit/", EditBankAccountView.as_view(), name="edit_bank_account"),
    path("bank-accounts/<uuid:pk>/toggle/", ToggleBankAccountView.as_view(), name="toggle_bank_account"),
    path("bank-accounts/<uuid:pk>/delete/", DeleteBankAccountView.as_view(), name="delete_bank_account"),
    path("bank-accounts/<uuid:pk>/ledger/", BankAccountLedgerView.as_view(), name="bank_account_ledger"),
    path("cash-position/", CashPositionView.as_view(), name="cash_position"),
    path("cash-position/aging/", AgingReportView.as_view(), name="aging_report"),
    path("kickbacks/", KickbacksView.as_view(), name="kickbacks"),
    path("kickbacks/add/", AddKickbackEntryView.as_view(), name="add_kickback_entry"),
    path("kickbacks/column-names/", KickbackColumnLabelsView.as_view(), name="kickback_column_labels"),
    path("kickbacks/<uuid:pk>/", KickbackDetailView.as_view(), name="kickback_detail"),
    path("kickbacks/<uuid:pk>/edit/", EditKickbackEntryView.as_view(), name="edit_kickback_entry"),
    path("kickbacks/<uuid:pk>/delete/", DeleteKickbackEntryView.as_view(), name="delete_kickback_entry"),
    path("kickbacks/export.csv", KickbackEntriesCsvView.as_view(), name="kickbacks_csv"),
    path("kickbacks/export.xlsx", KickbackEntriesExcelView.as_view(), name="kickbacks_excel"),
    path("kickbacks/export.pdf", KickbackEntriesPdfView.as_view(), name="kickbacks_pdf"),
    path("kickbacks/import/", ImportKickbackEntriesView.as_view(), name="import_kickback_entries"),
    path("kickbacks/import/sample.csv", KickbackImportSampleView.as_view(), name="kickbacks_import_sample"),
    path("ledgers/", LedgersView.as_view(), name="ledgers"),
    path("ledgers/general/add/", AddGeneralLedgerView.as_view(), name="add_general_ledger"),
    path("ledgers/general/<uuid:pk>/", GeneralLedgerDetailView.as_view(), name="general_ledger"),
    path("ledgers/general/<uuid:pk>/delete/", DeleteGeneralLedgerView.as_view(), name="delete_general_ledger"),
    path("ledgers/general/<uuid:pk>/entries/add/", AddLedgerEntryView.as_view(), name="add_ledger_entry"),
    path(
        "ledgers/general/<uuid:pk>/entries/<uuid:entry_pk>/delete/",
        DeleteLedgerEntryView.as_view(),
        name="delete_ledger_entry",
    ),
    path("ledgers/cash/", AccountLedgerView.as_view(account="CASH", account_label="Cash in Hand"), name="cash_ledger"),
    path("ledgers/bank/", AccountLedgerView.as_view(account="BANK", account_label="Bank"), name="bank_ledger"),
    path("ledgers/customers/<uuid:pk>/", CustomerLedgerView.as_view(), name="customer_ledger"),
    path("ledgers/vendors/<uuid:pk>/", VendorLedgerView.as_view(), name="vendor_ledger"),
    path("receivables/add/", AddReceivableView.as_view(), name="add_receivable"),
    path("receivables/<uuid:pk>/edit/", EditReceivableView.as_view(), name="edit_receivable"),
    path("receivables/<uuid:pk>/pay/", RecordReceivablePaymentView.as_view(), name="pay_receivable"),
    path("receivables/<uuid:pk>/delete/", DeleteReceivableView.as_view(), name="delete_receivable"),
    path("payables/add/", AddPayableView.as_view(), name="add_payable"),
    path("payables/<uuid:pk>/edit/", EditPayableView.as_view(), name="edit_payable"),
    path("payables/<uuid:pk>/pay/", RecordPayablePaymentView.as_view(), name="pay_payable"),
    path("payables/<uuid:pk>/delete/", DeletePayableView.as_view(), name="delete_payable"),
    path("partners/add/", AddPartnerView.as_view(), name="add_partner"),
    path("partners/transactions/add/", AddPartnerTransactionView.as_view(), name="add_partner_transaction"),
    path("partners/transactions/<uuid:pk>/edit/", EditPartnerTransactionView.as_view(), name="edit_partner_transaction"),
    path("partners/transactions/<uuid:pk>/delete/", DeletePartnerTransactionView.as_view(), name="delete_partner_transaction"),
    path("cash-position/partners/<uuid:pk>/", PartnerLedgerView.as_view(), name="partner_ledger"),
    path(
        "cash-position/partners/<uuid:pk>/export.xlsx",
        PartnerLedgerExcelView.as_view(),
        name="partner_ledger_excel",
    ),
    path(
        "cash-position/partners/<uuid:pk>/export.csv",
        PartnerLedgerCsvView.as_view(),
        name="partner_ledger_csv",
    ),
    path(
        "cash-position/partners/<uuid:pk>/export.pdf",
        PartnerLedgerPdfView.as_view(),
        name="partner_ledger_pdf",
    ),
]
