from django.urls import path

from .views import (
    AccountLedgerView,
    AddCategoryView,
    ApplyCouponView,
    AddCustomerView,
    AddExpenseView,
    AddPartnerView,
    AddPartnerTransactionView,
    AddPayableView,
    AddPurchaseView,
    AddReceivableView,
    AddSaleView,
    AddSubcategoryView,
    AddTransferView,
    AddVendorView,
    AnalyticsView,
    BillingView,
    BulkAddExpensesView,
    BulkAddPurchasesView,
    BulkAddSalesView,
    CancelAutopayView,
    CashPositionView,
    CategoriesView,
    CreateAutopaySubscriptionView,
    CreateInvoicePaymentOrderView,
    CustomerLedgerView,
    DailyBulkEntryView,
    DailyReportPdfView,
    DailyReportView,
    DashboardView,
    DeleteCategoryView,
    DeleteEntryView,
    DeletePartnerTransactionView,
    DeletePayableView,
    DeleteReceivableView,
    DeleteSubcategoryView,
    DeleteVendorView,
    EditCategoryView,
    EditEntryView,
    EditVendorView,
    EntriesView,
    FinanceSettingsView,
    LedgersView,
    PartnerLedgerView,
    PurchaseExpenseIntelligenceView,
    RecordPayablePaymentView,
    RecordReceivablePaymentView,
    ReportsView,
    SalesIntelligenceView,
    StatementPdfView,
    ToggleCategoryView,
    ToggleCustomerView,
    ToggleSubcategoryView,
    ToggleVendorView,
    VendorLedgerView,
    VendorsView,
    VerifyAutopaySetupView,
    VerifyInvoicePaymentView,
)

app_name = "finance"

urlpatterns = [
    path("", DashboardView.as_view(), name="dashboard"),
    path("billing/", BillingView.as_view(), name="billing"),
    path(
        "billing/invoices/<int:pk>/pay/order/",
        CreateInvoicePaymentOrderView.as_view(),
        name="create_invoice_payment_order",
    ),
    path(
        "billing/invoices/<int:pk>/pay/verify/",
        VerifyInvoicePaymentView.as_view(),
        name="verify_invoice_payment",
    ),
    path(
        "billing/invoices/<int:pk>/coupon/",
        ApplyCouponView.as_view(),
        name="apply_coupon",
    ),
    path("billing/autopay/create/", CreateAutopaySubscriptionView.as_view(), name="create_autopay_subscription"),
    path("billing/autopay/verify/", VerifyAutopaySetupView.as_view(), name="verify_autopay_setup"),
    path("billing/autopay/cancel/", CancelAutopayView.as_view(), name="cancel_autopay"),
    path("analytics/", AnalyticsView.as_view(), name="analytics"),
    path("sales-intelligence/", SalesIntelligenceView.as_view(), name="sales_intelligence"),
    path(
        "purchase-expense-intelligence/",
        PurchaseExpenseIntelligenceView.as_view(),
        name="purchase_expense_intelligence",
    ),
    path("daily/", DailyReportView.as_view(), name="daily_report"),
    path("daily/pdf", DailyReportPdfView.as_view(), name="daily_report_pdf"),
    path("daily/bulk-entry/", DailyBulkEntryView.as_view(), name="daily_bulk_entry"),
    path("daily/bulk-sales/", BulkAddSalesView.as_view(), name="bulk_add_sales"),
    path("daily/bulk-expenses/", BulkAddExpensesView.as_view(), name="bulk_add_expenses"),
    path("daily/bulk-purchases/", BulkAddPurchasesView.as_view(), name="bulk_add_purchases"),
    path("sales/add/", AddSaleView.as_view(), name="add_sale"),
    path("expenses/add/", AddExpenseView.as_view(), name="add_expense"),
    path("purchases/add/", AddPurchaseView.as_view(), name="add_purchase"),
    path("transfers/add/", AddTransferView.as_view(), name="add_transfer"),
    path("entries/", EntriesView.as_view(), name="entries"),
    path("entries/<str:entry_type>/<uuid:pk>/edit/", EditEntryView.as_view(), name="edit_entry"),
    path("entries/<str:entry_type>/<uuid:pk>/delete/", DeleteEntryView.as_view(), name="delete_entry"),
    path("reports/", ReportsView.as_view(), name="reports"),
    path("reports/pnl.pdf", StatementPdfView.as_view(statement="pnl"), name="pnl_pdf"),
    path(
        "reports/balance-sheet.pdf",
        StatementPdfView.as_view(statement="balance_sheet"),
        name="balance_sheet_pdf",
    ),
    path("reports/cash-flow.pdf", StatementPdfView.as_view(statement="cash_flow"), name="cash_flow_pdf"),
    path("settings/", FinanceSettingsView.as_view(), name="settings"),
    path("categories/", CategoriesView.as_view(), name="categories"),
    path("categories/add/", AddCategoryView.as_view(), name="add_category"),
    path("categories/<uuid:pk>/edit/", EditCategoryView.as_view(), name="edit_category"),
    path("categories/<uuid:pk>/toggle/", ToggleCategoryView.as_view(), name="toggle_category"),
    path("categories/<uuid:pk>/delete/", DeleteCategoryView.as_view(), name="delete_category"),
    path("subcategories/add/", AddSubcategoryView.as_view(), name="add_subcategory"),
    path("subcategories/<uuid:pk>/toggle/", ToggleSubcategoryView.as_view(), name="toggle_subcategory"),
    path("subcategories/<uuid:pk>/delete/", DeleteSubcategoryView.as_view(), name="delete_subcategory"),
    path("customers/add/", AddCustomerView.as_view(), name="add_customer"),
    path("customers/<uuid:pk>/toggle/", ToggleCustomerView.as_view(), name="toggle_customer"),
    path("vendors/", VendorsView.as_view(), name="vendors"),
    path("vendors/add/", AddVendorView.as_view(), name="add_vendor"),
    path("vendors/<uuid:pk>/edit/", EditVendorView.as_view(), name="edit_vendor"),
    path("vendors/<uuid:pk>/toggle/", ToggleVendorView.as_view(), name="toggle_vendor"),
    path("vendors/<uuid:pk>/delete/", DeleteVendorView.as_view(), name="delete_vendor"),
    path("cash-position/", CashPositionView.as_view(), name="cash_position"),
    path("ledgers/", LedgersView.as_view(), name="ledgers"),
    path("ledgers/cash/", AccountLedgerView.as_view(account="CASH", account_label="Cash in Hand"), name="cash_ledger"),
    path("ledgers/bank/", AccountLedgerView.as_view(account="BANK", account_label="Bank"), name="bank_ledger"),
    path("ledgers/customers/<uuid:pk>/", CustomerLedgerView.as_view(), name="customer_ledger"),
    path("ledgers/vendors/<uuid:pk>/", VendorLedgerView.as_view(), name="vendor_ledger"),
    path("receivables/add/", AddReceivableView.as_view(), name="add_receivable"),
    path("receivables/<uuid:pk>/pay/", RecordReceivablePaymentView.as_view(), name="pay_receivable"),
    path("receivables/<uuid:pk>/delete/", DeleteReceivableView.as_view(), name="delete_receivable"),
    path("payables/add/", AddPayableView.as_view(), name="add_payable"),
    path("payables/<uuid:pk>/pay/", RecordPayablePaymentView.as_view(), name="pay_payable"),
    path("payables/<uuid:pk>/delete/", DeletePayableView.as_view(), name="delete_payable"),
    path("partners/add/", AddPartnerView.as_view(), name="add_partner"),
    path("partners/transactions/add/", AddPartnerTransactionView.as_view(), name="add_partner_transaction"),
    path("partners/transactions/<uuid:pk>/delete/", DeletePartnerTransactionView.as_view(), name="delete_partner_transaction"),
    path("cash-position/partners/<uuid:pk>/", PartnerLedgerView.as_view(), name="partner_ledger"),
]
