"""Pure-Python, restorable SQL dump of one tenant schema.

Emits plain SQL (`psql -f dump.sql`) containing the schema, sequences,
tables, data, constraints and indexes. It deliberately does not shell out
to `pg_dump`, which isn't guaranteed to exist on the app host.
"""
from __future__ import annotations

import datetime
from typing import Iterator

from django.db import connections

from .utils import SCHEMA_RE, TenantSchemaError

BATCH = 500


def _q(name: str) -> str:
    return '"' + name.replace('"', '""') + '"'


def _lit(raw_cursor, value) -> str:
    out = raw_cursor.mogrify("%s", (value,))
    return out.decode() if isinstance(out, bytes) else out


def dump_schema_sql(schema: str, using: str = "default") -> Iterator[str]:
    if not SCHEMA_RE.match(schema):
        raise TenantSchemaError("Invalid schema name.")

    conn = connections[using]
    with conn.cursor() as cur:
        raw = cur.cursor  # underlying psycopg2 cursor, for mogrify()

        def rows(query, params=()):
            cur.execute(query, params)
            return cur.fetchall()

        now = datetime.datetime.now(datetime.timezone.utc).isoformat()
        yield f"-- Backup of schema {schema}\n-- Generated {now}\n"
        yield "-- Restore with: psql -d <database> -f <this file>\n\n"
        yield "SET statement_timeout = 0;\nSET client_encoding = 'UTF8';\nSET standard_conforming_strings = on;\n\n"
        yield f"CREATE SCHEMA IF NOT EXISTS {_q(schema)};\nSET search_path TO {_q(schema)}, public;\n\n"

        seqs = rows(
            """
            SELECT s.sequencename, format_type(s.data_type, NULL), s.start_value, s.min_value,
                   s.max_value, s.increment_by, s.cycle, s.cache_size, s.last_value
            FROM pg_sequences s
            WHERE s.schemaname = %s
            ORDER BY s.sequencename
            """,
            [schema],
        )
        # Sequences owned by an identity column are recreated by the column itself.
        identity_seqs = {
            r[0]
            for r in rows(
                """
                SELECT c.relname FROM pg_class c
                JOIN pg_namespace n ON n.oid = c.relnamespace
                JOIN pg_depend d ON d.objid = c.oid AND d.deptype = 'i'
                WHERE c.relkind = 'S' AND n.nspname = %s
                """,
                [schema],
            )
        }
        for name, dtype, start, minv, maxv, inc, cycle, cache, _last in seqs:
            if name in identity_seqs:
                continue
            yield (
                f"CREATE SEQUENCE {_q(schema)}.{_q(name)} AS {dtype} INCREMENT BY {inc} "
                f"MINVALUE {minv} MAXVALUE {maxv} START WITH {start} CACHE {cache}"
                f"{' CYCLE' if cycle else ''};\n"
            )
        yield "\n"

        tables = [
            r[0]
            for r in rows(
                """
                SELECT c.relname FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
                WHERE n.nspname = %s AND c.relkind IN ('r', 'p') ORDER BY c.relname
                """,
                [schema],
            )
        ]

        columns_by_table = {}
        for table in tables:
            cols = rows(
                """
                SELECT a.attname, format_type(a.atttypid, a.atttypmod), a.attnotnull,
                       pg_get_expr(d.adbin, d.adrelid), a.attidentity, a.attgenerated
                FROM pg_attribute a
                JOIN pg_class c ON c.oid = a.attrelid
                JOIN pg_namespace n ON n.oid = c.relnamespace
                LEFT JOIN pg_attrdef d ON d.adrelid = a.attrelid AND d.adnum = a.attnum
                WHERE n.nspname = %s AND c.relname = %s AND a.attnum > 0 AND NOT a.attisdropped
                ORDER BY a.attnum
                """,
                [schema, table],
            )
            columns_by_table[table] = cols
            defs = []
            for name, ctype, notnull, default, identity, generated in cols:
                line = f"    {_q(name)} {ctype}"
                if identity == "a":
                    line += " GENERATED ALWAYS AS IDENTITY"
                elif identity == "d":
                    line += " GENERATED BY DEFAULT AS IDENTITY"
                elif generated == "s":
                    line += f" GENERATED ALWAYS AS ({default}) STORED"
                elif default is not None:
                    line += f" DEFAULT {default}"
                if notnull:
                    line += " NOT NULL"
                defs.append(line)
            yield f"CREATE TABLE {_q(schema)}.{_q(table)} (\n" + ",\n".join(defs) + "\n);\n\n"

        for table in tables:
            cols = [c for c in columns_by_table[table] if c[5] != "s"]
            if not cols:
                continue
            names = ", ".join(_q(c[0]) for c in cols)
            override = " OVERRIDING SYSTEM VALUE" if any(c[4] == "a" for c in cols) else ""
            cur.execute(f"SELECT {names} FROM {_q(schema)}.{_q(table)}")
            wrote = False
            while True:
                batch = cur.fetchmany(BATCH)
                if not batch:
                    break
                if not wrote:
                    yield f"-- Data for {table}\n"
                    wrote = True
                values = ",\n".join(
                    "(" + ", ".join(_lit(raw, v) for v in row) + ")" for row in batch
                )
                yield f"INSERT INTO {_q(schema)}.{_q(table)} ({names}){override} VALUES\n{values};\n"
            if wrote:
                yield "\n"

        # Primary/unique/check first, foreign keys last (after all data is in).
        constraints = rows(
            """
            SELECT c.relname, con.conname, pg_get_constraintdef(con.oid), con.contype
            FROM pg_constraint con
            JOIN pg_class c ON c.oid = con.conrelid
            JOIN pg_namespace n ON n.oid = c.relnamespace
            WHERE n.nspname = %s AND con.contype IN ('p', 'u', 'c', 'f', 'x')
            ORDER BY c.relname, con.conname
            """,
            [schema],
        )
        constraint_names = {r[1] for r in constraints}
        for wanted_fk in (False, True):
            for table, name, definition, ctype in constraints:
                if (ctype == "f") == wanted_fk:
                    yield f"ALTER TABLE ONLY {_q(schema)}.{_q(table)} ADD CONSTRAINT {_q(name)} {definition};\n"
        yield "\n"

        for name, definition in rows(
            "SELECT indexname, indexdef FROM pg_indexes WHERE schemaname = %s ORDER BY indexname",
            [schema],
        ):
            if name not in constraint_names:
                yield definition + ";\n"
        yield "\n"

        for seq in seqs:
            name, last = seq[0], seq[-1]
            if last is not None:
                yield f"SELECT setval('{_q(schema)}.{_q(name)}'::regclass, {last}, true);\n"


# --- pg_restore-compatible archive (custom format) -----------------------

import glob
import os
import shutil
import subprocess
import tempfile


def find_pg_dump() -> str | None:
    """Locate a pg_dump binary: PG_DUMP_PATH, PATH, then common Windows installs."""
    explicit = os.environ.get("PG_DUMP_PATH")
    if explicit and os.path.isfile(explicit):
        return explicit
    found = shutil.which("pg_dump")
    if found:
        return found
    patterns = [
        r"C:\Program Files\PostgreSQL\*\bin\pg_dump.exe",
        r"C:\Program Files\PostgreSQL\*\pgAdmin 4\runtime\pg_dump.exe",
    ]
    for pattern in patterns:
        matches = sorted(glob.glob(pattern), reverse=True)
        if matches:
            return matches[0]
    return None


def dump_schema_archive(schema: str, using: str = "default") -> str:
    """Run `pg_dump -Fc` for one schema into a temp file and return its path.

    Custom format is what pgAdmin's Restore dialog and `pg_restore` expect.
    The caller must delete the file. Raises TenantSchemaError on failure.
    """
    if not SCHEMA_RE.match(schema):
        raise TenantSchemaError("Invalid schema name.")
    binary = find_pg_dump()
    if binary is None:
        raise TenantSchemaError("pg_dump is not available on this server.")

    settings = connections[using].settings_dict
    fd, path = tempfile.mkstemp(suffix=".dump")
    os.close(fd)
    cmd = [
        binary, "--format=custom", "--no-owner", "--no-privileges",
        f"--schema={schema}",
        "--host", str(settings["HOST"]), "--port", str(settings["PORT"]),
        "--username", settings["USER"], "--dbname", settings["NAME"],
        "--file", path,
    ]
    env = dict(os.environ, PGPASSWORD=settings["PASSWORD"])
    sslmode = (settings.get("OPTIONS") or {}).get("sslmode")
    if sslmode:
        env["PGSSLMODE"] = sslmode
    result = subprocess.run(cmd, env=env, capture_output=True, text=True, timeout=600)
    if result.returncode != 0:
        os.unlink(path)
        raise TenantSchemaError(f"pg_dump failed: {result.stderr.strip()[:500]}")
    return path
