# Generated by Django 5.2.14 on 2026-09-11 19:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('organization_code', models.CharField(max_length=12, unique=True)),
                ('schema_name', models.CharField(max_length=63, unique=True)),
                ('business_type', models.CharField(choices=[('RETAIL', 'Retail / Store'), ('RESTAURANT', 'Restaurant / Food Service'), ('ECOMMERCE', 'E-commerce'), ('SERVICES', 'Professional Services'), ('MANUFACTURING', 'Manufacturing'), ('WHOLESALE', 'Wholesale / Distribution'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('size', models.CharField(choices=[('SOLO', 'Just me'), ('SMALL', '2-10 employees'), ('MEDIUM', '11-50 employees'), ('LARGE', '51-200 employees'), ('ENTERPRISE', '200+ employees')], default='SOLO', max_length=20)),
                ('currency', models.CharField(default='INR', max_length=8)),
                ('timezone', models.CharField(default='Asia/Kolkata', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
