# Generated by Django 5.2.14 on 2026-09-14 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_organization_address_organization_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='service_status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=10),
        ),
        migrations.CreateModel(
            name='ServiceStatusChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performed_by_email', models.EmailField(max_length=254)),
                ('action', models.CharField(choices=[('START', 'Start Service'), ('STOP', 'Stop Service'), ('SUSPEND', 'Suspend Service'), ('RESUME', 'Resume Service')], max_length=10)),
                ('previous_status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended')], max_length=10)),
                ('new_status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended')], max_length=10)),
                ('reason', models.CharField(blank=True, choices=[('PAYMENT_OVERDUE', 'Payment overdue'), ('CUSTOMER_REQUESTED', 'Customer requested'), ('ADMINISTRATIVE', 'Administrative action'), ('MAINTENANCE', 'Maintenance'), ('SECURITY', 'Security'), ('OTHER', 'Other')], max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_status_changes', to='organizations.organization')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', '-created_at'], name='organizatio_organiz_f99b0e_idx')],
            },
        ),
    ]
