# Generated by Django 5.2.14 on 2026-09-17 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_organization_service_status_servicestatuschange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='business_type',
            field=models.CharField(choices=[('RETAIL_ECOMMERCE', 'Retail & E-commerce'), ('MANUFACTURING', 'Manufacturing'), ('HEALTHCARE', 'Healthcare & Medical'), ('TECHNOLOGY', 'Technology & Software'), ('PROFESSIONAL_SERVICES', 'Professional Services'), ('FINANCIAL_SERVICES', 'Financial Services'), ('REAL_ESTATE', 'Real Estate'), ('CONSTRUCTION', 'Construction & Engineering'), ('EDUCATION', 'Education & Training'), ('RESTAURANTS_FOOD', 'Restaurants & Food Services'), ('HOSPITALITY_TRAVEL', 'Hospitality & Travel'), ('LOGISTICS_TRANSPORT', 'Logistics & Transportation'), ('WHOLESALE_DISTRIBUTION', 'Wholesale & Distribution'), ('AUTOMOTIVE', 'Automotive'), ('MEDIA_ENTERTAINMENT', 'Media & Entertainment'), ('MARKETING_ADVERTISING', 'Marketing & Advertising'), ('AGRICULTURE', 'Agriculture & Farming'), ('PHARMA_LIFE_SCIENCES', 'Pharmaceuticals & Life Sciences'), ('ENERGY_UTILITIES', 'Energy & Utilities'), ('OTHER', 'Other')], default='OTHER', max_length=30),
        ),
    ]
