# Generated by Django 5.2.14 on 2026-09-21 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_alter_organization_business_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicestatuschange',
            name='reason',
            field=models.CharField(blank=True, choices=[('PAYMENT_OVERDUE', 'Payment pending / overdue'), ('CUSTOMER_REQUESTED', 'Customer requested'), ('ADMINISTRATIVE', 'Administrative action'), ('MAINTENANCE', 'Maintenance'), ('SECURITY', 'Security'), ('OTHER', 'Other')], max_length=32),
        ),
    ]
