# Generated by Django 5.2.14 on 2026-09-22 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_alter_servicestatuschange_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='historical_entry_window_months',
            field=models.PositiveIntegerField(blank=True, help_text="Months back this org may backdate a sales/purchase/expense entry. Blank = use the plan's default. 0 = no limit. Superadmin-only.", null=True),
        ),
    ]
