# Generated by Django 5.2.14 on 2026-09-23 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_organization_historical_entry_window_months'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='historical_entry_window_months',
        ),
        migrations.AddField(
            model_name='organization',
            name='historical_entry_cutoff_date',
            field=models.DateField(blank=True, help_text="Fixed date before which this org may not backdate a sales/purchase/expense entry. Blank = use the plan's rolling default. Ignored when 'No backdating limit' is checked. Superadmin-only.", null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='historical_entry_no_limit',
            field=models.BooleanField(default=False, help_text='Lets this org backdate an entry to any date, overriding both the plan default and the cutoff date above. Superadmin-only.'),
        ),
    ]
