# Generated by Django 5.2.14 on 2026-09-24 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_remove_organization_historical_entry_window_months_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='bank_account_holder',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='organization',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=34),
        ),
        migrations.AddField(
            model_name='organization',
            name='bank_ifsc',
            field=models.CharField(blank=True, max_length=11, verbose_name='IFSC code'),
        ),
        migrations.AddField(
            model_name='organization',
            name='bank_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='organization',
            name='employee_count',
            field=models.PositiveIntegerField(blank=True, help_text='Exact headcount, if known — separate from the team-size range above.', null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='org_logos/'),
        ),
        migrations.AddField(
            model_name='organization',
            name='pan_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='PAN number'),
        ),
        migrations.AddField(
            model_name='organization',
            name='registered_address',
            field=models.CharField(blank=True, help_text='Leave blank if the same as the operating address above.', max_length=255),
        ),
    ]
