# Generated by Django 5.2.14 on 2026-09-24 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0008_organization_bank_account_holder_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='logo',
        ),
    ]
