# Generated by Django 5.2.12 on 2026-10-03 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0009_remove_organization_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='db_type',
            field=models.CharField(choices=[('SHARED_SCHEMA', 'Shared (legacy)'), ('SQLITE', 'Private database file'), ('EXTERNAL_POSTGRES', 'Your own PostgreSQL server')], default='SHARED_SCHEMA', max_length=20),
        ),
        migrations.CreateModel(
            name='TenantDatabaseCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=255)),
                ('port', models.PositiveIntegerField(default=5432)),
                ('database', models.CharField(max_length=63)),
                ('username', models.CharField(max_length=63)),
                ('password_encrypted', models.BinaryField()),
                ('sslmode', models.CharField(default='require', max_length=20)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='db_credential', to='organizations.organization')),
            ],
        ),
    ]
