# Generated by Django 5.2.12 on 2026-10-03 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0010_organization_db_type_tenantdatabasecredential'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='db_type',
            field=models.CharField(choices=[('SHARED_SCHEMA', 'Shared (legacy)'), ('SQLITE', 'Private database file')], default='SHARED_SCHEMA', max_length=20),
        ),
        migrations.DeleteModel(
            name='TenantDatabaseCredential',
        ),
    ]
