# Generated by Django 5.2.12 on 2026-10-03 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0011_alter_organization_db_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudBackupConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('GOOGLE_DRIVE', 'Google Drive')], default='GOOGLE_DRIVE', max_length=20)),
                ('access_token_encrypted', models.BinaryField()),
                ('refresh_token_encrypted', models.BinaryField()),
                ('token_expires_at', models.DateTimeField()),
                ('external_folder_id', models.CharField(max_length=128)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_error', models.CharField(blank=True, max_length=500)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cloud_backup', to='organizations.organization')),
            ],
        ),
    ]
