# Generated by Django 5.2.12 on 2026-10-03 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0012_cloudbackupconnection'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudbackupconnection',
            name='external_file_id',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
