# Generated by Django 5.2.12 on 2026-10-03 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0013_cloudbackupconnection_external_file_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='db_type',
            field=models.CharField(choices=[('SHARED_SCHEMA', 'Shared (legacy)'), ('SQLITE', 'Private database file (legacy)'), ('GOOGLE_SHEETS', 'Your own Google Sheet')], default='SHARED_SCHEMA', max_length=20),
        ),
    ]
