# Generated by Django 5.2.12 on 2026-10-03 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0014_alter_organization_db_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='db_type',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='schema_name',
        ),
    ]
