# Generated by Django 5.2.12 on 2026-10-05 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0016_organization_storage_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='manager_logins',
            field=models.PositiveSmallIntegerField(choices=[('1', '1 manager account'), ('2', '2 manager accounts')], default=1, help_text='Number of manager accounts for this organization'),
        ),
    ]
