# Generated by Django 5.2.12 on 2026-10-06 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0017_organization_manager_logins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='manager_logins',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 Admin account'), (2, '1 Admin + 1 manager account')], default=1, help_text='Number of manager accounts for this organization'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='storage_mode',
            field=models.CharField(choices=[('OUR_DATABASE', "Finday's secure managed database"), ('GOOGLE_SHEETS', 'Your own Google Drive')], default='GOOGLE_SHEETS', max_length=20),
        ),
        migrations.CreateModel(
            name='DataStorageChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_storage', models.CharField(choices=[('OUR_DATABASE', "Finday's secure managed database"), ('GOOGLE_SHEETS', 'Your own Google Drive')], max_length=20)),
                ('requested_storage', models.CharField(choices=[('OUR_DATABASE', "Finday's secure managed database"), ('GOOGLE_SHEETS', 'Your own Google Drive')], max_length=20)),
                ('current_monthly_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('requested_monthly_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price_difference', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('reason', models.TextField(blank=True, help_text='Why the client wants to change storage')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Superadmin notes on approval/rejection')),
                ('reviewed_by_email', models.EmailField(blank=True, max_length=254)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_change_requests', to='organizations.organization')),
            ],
            options={
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['organization', '-requested_at'], name='organizatio_organiz_648727_idx'), models.Index(fields=['status', '-requested_at'], name='organizatio_status_fac8fe_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['PENDING', 'APPROVED'])), fields=('organization', 'status'), name='unique_active_storage_request')],
            },
        ),
    ]
