# Generated by Django 5.2.12 on 2026-10-06 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0018_alter_organization_manager_logins_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datastoragechangerequest',
            name='current_plan_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='datastoragechangerequest',
            name='requested_plan_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
