# Generated by Django 5.2.12 on 2026-10-07 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0020_storage_request_cancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudbackupconnection',
            name='connected_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
